### ISSUE TITLE
i can't compile

### ISSUE THREAD

**Issue by gilles007-** [cristianst85/QuickConnectPlugin#34]
hello
i have the same problem in issue #31 
i don't have the file "GeneratedAssemblyInfo.cs"
and i got an error with the task GitVersion.
I have installed git for windows
I think it's 2 different problems

**Comment by gilles007-** [comment]
so i have edited and modified a lot of files to remove references
i can now compile without this file and errors
then i run build.bat to generate the plugin (after editing it to remove check)

**Comment by cristianst85** [comment]
Hello.

As I said before GeneratedAssemblyInfo.cs is auto-generated when the solution is being built.

Can you provide more information?
 
Which version of Visual Studio are you using?
Which version of Git do you have?
Can you post the error(s) or some screenshots?
Are you trying to build from a fresh Git clone?
Etc.

Otherwise it's impossible for me to say what is going on your machine.

P.S. I can build the solution without any issues/errors using Visual Studio 2017 Community Version 15.9.47 (which is the latest version at the moment of writing this message) on a Windows 10 machine.

**Comment by gilles007-** [comment]
_As I said before GeneratedAssemblyInfo.cs is auto-generated when the solution is being built._
this is the problem : the file is not auto-generated.
why not provide this file directly ?

_Which version of Visual Studio are you using?_
Visual Studio 2019 here (16.5.4), deprecated if i trust the message on top
Visual Studio 2022 is current today

_Which version of Git do you have?_
I downloaded the last version : Git-2.36.0-64-bit.exe

_Can you post the error(s) or some screenshots?_
same errors and screenshot in #31

_Are you trying to build from a fresh Git clone?_
I download source code from release section, unzip it to desktop and click on QuickConnectPlugin.sln

As a workaround, i have removed references to Git and GeneratedAssemblyInfo.cs to been able to compile without errors

**Comment by cristianst85** [comment]
The whole idea for GeneratedAssemblyInfo.cs being generated at build time is because it contains versioning information that is dynamic, i.e., the plugin full version also includes the Git HEAD commit (and branch name).

![image](https://user-images.githubusercontent.com/12585988/164337154-86ef8261-25cf-448e-be30-580e4eca47a5.png)

_I download source code from release section, unzip it to desktop and click on QuickConnectPlugin.sln_
You are doing it wrong. You should clone the repository using Git. This is the reason why you have an error and cannot build it. When you download the source code from the release section it is not contained within a Git repository hence the error.

![image](https://user-images.githubusercontent.com/12585988/164338264-123a1b23-866a-4d11-babc-ab8c184969f4.png)
