### ISSUE TITLE
Plugin can't load - VMWare missing DLL

### ISSUE THREAD

**Issue by JonTheNiceGuy** [cristianst85/QuickConnectPlugin#8]
I get the following message:

Could not find a part of the path 'C:\Program Files (x86)\VMWare\Infrastructure\vSphere PowerCLI\VMware.Vim.dll'. mscorlib

I have the vSphere 5.0 client loaded (in C:\Program Files (x86)\VMware\Infrastructure\Virtual Infrastructure Client), but not this part?

**Comment by cristianst85** [comment]
Hi, @JonTheNiceGuy. Thank you for reporting this.

I'm assuming that you are using the .plgx version of the plugin, so you'll need to install [vSphere PowerCLI version 5.8.0](https://developercenter.vmware.com/tool/vsphere_powercli/5.8.0) (see [dev](https://github.com/cristianst85/QuickConnectPlugin/tree/dev#requirements-1)).

Otherwise, you can use the .dll version instead and the plugin will load just fine.

**Comment by cristianst85** [comment]
I'm changing the code to dynamically load `VMware.Vim.dll` at runtime. This way the .plgx can be used without having to install **vSphere PowerCLI**.

Any thoughts on this?

P.S. _vSphere PowerCLI_ is required only to change passwords for ESXi hosts.

**Comment by JonTheNiceGuy** [comment]
I think that's fine, and to be honest, I think it would have been fine if you'd mentioned the additional requirement, it wouldn't have been a problem, but if it isn't required, so much the better!

**Comment by cristianst85** [comment]
I've just released a new [version](https://github.com/cristianst85/QuickConnectPlugin/releases/tag/0.4.0-rc.2) that fixes the addressed issue.

Thanks again.
